language: go
dist: trusty
sudo: false
go:
- 1.8.3
- 1.9
- tip

script:
- git clone -b dev https://github.com/Bytom/bytom.git $GOPATH/src/github.com/bytom
- cd $GOPATH/src/github.com/bytom
- make install
- make test
