send_acct_id = "0CR42O4A00A02"
password = "123456"
send_asset_id = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
#"issue", "spend", "address"
build_type = "address"
asset_receiver = ["tm1qvujkjf8q832c7g60qgacmef59ea8q2zelaa0z5"]
#asset_receiver = ["bm1q678m0eac5xcxxvalynzjp5cl4wq06rp039svzs","bm1qhgpjl0f7hzyxj866v0ztllscw6uqmh5gfcuqgy"]
